# Generated by Django 2.2.2 on 2019-08-12 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedInstitutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('target_audience', models.IntegerField(choices=[(1, 'dzieci'), (2, 'samotne_matki'), (3, 'bezdomni'), (4, 'niepełnosprawni'), (5, 'osoby_starsze'), (6, 'bezrobotni'), (7, 'all')])),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UsersDonations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_donations', models.IntegerField(default=0)),
                ('number_bags', models.IntegerField(default=0)),
                ('number_institutions', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.IntegerField(choices=[(1, 'ubrania, które nadają się do ponownego użycia'), (2, 'ubrania do wyrzucenia'), (3, 'zabawki'), (4, 'książki'), (5, 'inne')])),
                ('number_of_bags', models.IntegerField(default=0)),
                ('recipient_type', models.IntegerField(choices=[(1, 'dzieci'), (2, 'samotne_matki'), (3, 'bezdomni'), (4, 'niepełnosprawni'), (5, 'osoby_starsze'), (6, 'bezrobotni'), (7, 'all')])),
                ('city', models.CharField(max_length=64)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('pickup_address', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=64)),
                ('pickup_date', models.DateField()),
                ('pickup_hour', models.DateTimeField()),
                ('transprt_notes', models.TextField()),
                ('transfer_status', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oddaj_ciuszek.TrustedInstitutions')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
